apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 0
      volumes:
        - name: nfs-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud-server-pvc
        - name: nextcloud-ssl
          secret:
            secretName: nextcloud-net-tls
      containers:
        - image: ghcr.io/linuxserver/nextcloud
          name: nextcloud
          imagePullPolicy: Always
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Moscow
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          volumeMounts:
            - mountPath: /config
              name: nfs-nextcloud
              subPath: config
            - mountPath: /data
              name: nfs-nextcloud
              subPath: data
            - mountPath: /var/www/html
              name: nfs-nextcloud
              subPath: html
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-service
  namespace: nextcloud
spec:
  type: LoadBalancer
  selector:
    app: nextcloud
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443