kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-server-pvc
  namespace: nextcloud
spec:
  volumeName: nextcloud-server-pv-nfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi